version: "3.8"

services: 
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /Users/angelivanov/smart-brain-api
    environment:
      POSTGRES_URI: postgres://angel:secret@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./:/Users/angelivanov/smart-brain-api

  postgres:
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - "5432:5432"

  redis:  
    image: redis
    ports:
      - "6379:6379"